[package]
name = "bam_binary"
version = "0.1.0"
authors = ["nickr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
bam_tools = {path = "../bam_tools"}